package com.taximet.pro;
import android.Manifest; import android.content.*; import android.content.pm.PackageManager; import android.location.LocationManager; import android.os.Build; import androidx.core.app.ActivityCompat; import androidx.core.content.ContextCompat; import com.getcapacitor.*; import com.getcapacitor.annotation.CapacitorPlugin;
@CapacitorPlugin(name="TaximetLocation")
public class TaximetLocationPlugin extends Plugin {
 public static final String ACTION_LOCATION="com.taximet.pro.LOCATION", ACTION_ERROR="com.taximet.pro.LOCATION_ERROR", ACTION_STATUS="com.taximet.pro.GPS_STATUS"; private BroadcastReceiver receiver;
 @Override public void load(){super.load(); receiver=new BroadcastReceiver(){@Override public void onReceive(Context c,Intent i){String a=i.getAction(); if(ACTION_LOCATION.equals(a))notifyListeners("locationUpdate",payload(i)); else if(ACTION_ERROR.equals(a))notifyListeners("locationError",payload(i)); else if(ACTION_STATUS.equals(a))notifyListeners("gpsStatus",payload(i));}}; IntentFilter f=new IntentFilter();f.addAction(ACTION_LOCATION);f.addAction(ACTION_ERROR);f.addAction(ACTION_STATUS);ContextCompat.registerReceiver(getContext(),receiver,f,ContextCompat.RECEIVER_NOT_EXPORTED);}
 @Override protected void handleOnDestroy(){if(receiver!=null){try{getContext().unregisterReceiver(receiver);}catch(Exception ignored){}receiver=null;}super.handleOnDestroy();}
 private JSObject payload(Intent i){JSObject o=new JSObject();if(i.hasExtra("latitude"))o.put("latitude",i.getDoubleExtra("latitude",0));if(i.hasExtra("longitude"))o.put("longitude",i.getDoubleExtra("longitude",0));if(i.hasExtra("accuracy"))o.put("accuracy",i.getDoubleExtra("accuracy",999));if(i.hasExtra("speedMps"))o.put("speedMps",i.getDoubleExtra("speedMps",-1));if(i.hasExtra("heading"))o.put("heading",i.getDoubleExtra("heading",-1));if(i.hasExtra("timestamp"))o.put("timestamp",i.getLongExtra("timestamp",0));if(i.hasExtra("code"))o.put("code",i.getIntExtra("code",2));if(i.hasExtra("message"))o.put("message",i.getStringExtra("message"));if(i.hasExtra("authorization"))o.put("authorization",i.getStringExtra("authorization"));if(i.hasExtra("servicesEnabled"))o.put("servicesEnabled",i.getBooleanExtra("servicesEnabled",false));if(i.hasExtra("started"))o.put("started",i.getBooleanExtra("started",false));return o;}
 private boolean hasPermission(){return ContextCompat.checkSelfPermission(getContext(),Manifest.permission.ACCESS_FINE_LOCATION)==PackageManager.PERMISSION_GRANTED||ContextCompat.checkSelfPermission(getContext(),Manifest.permission.ACCESS_COARSE_LOCATION)==PackageManager.PERMISSION_GRANTED;}
 @PluginMethod public void start(PluginCall call){if(!hasPermission()){ActivityCompat.requestPermissions(getActivity(),new String[]{Manifest.permission.ACCESS_FINE_LOCATION,Manifest.permission.ACCESS_COARSE_LOCATION},4401);call.resolve(new JSObject().put("status","REQUESTING_PERMISSION"));return;}try{Intent i=new Intent(getContext(),TaximetLocationService.class);if(Build.VERSION.SDK_INT>=26)ContextCompat.startForegroundService(getContext(),i);else getContext().startService(i);call.resolve(new JSObject().put("status","STARTED"));}catch(Exception e){call.resolve(new JSObject().put("status","ERROR").put("message",e.getMessage()));}}
 @PluginMethod public void stop(PluginCall call){getContext().stopService(new Intent(getContext(),TaximetLocationService.class));call.resolve(new JSObject().put("status","STOPPED"));}
 @PluginMethod public void getLastLocation(PluginCall call){SharedPreferences p=getContext().getSharedPreferences("taximet_gps",0);JSObject o=new JSObject();if(!p.contains("lat")||!p.contains("lon")){call.resolve(o);return;}o.put("latitude",p.getFloat("lat",0));o.put("longitude",p.getFloat("lon",0));o.put("accuracy",p.getFloat("accuracy",999));o.put("speedMps",p.getFloat("speedMps",-1));o.put("heading",p.getFloat("heading",-1));o.put("timestamp",p.getLong("timestamp",0));call.resolve(o);}
 @PluginMethod public void status(PluginCall call){SharedPreferences p=getContext().getSharedPreferences("taximet_gps",0);LocationManager lm=(LocationManager)getContext().getSystemService(Context.LOCATION_SERVICE);boolean enabled=false;try{enabled=lm!=null&&(lm.isProviderEnabled(LocationManager.GPS_PROVIDER)||lm.isProviderEnabled(LocationManager.NETWORK_PROVIDER));}catch(Exception ignored){}call.resolve(new JSObject().put("authorization",hasPermission()?"AUTHORIZED":"DENIED").put("servicesEnabled",enabled).put("started",p.getBoolean("started",false)).put("hasFix",p.contains("lat")&&p.contains("lon")).put("accuracy",p.getFloat("accuracy",999)).put("timestamp",p.getLong("timestamp",0)));}
}
