package com.taximet.pro;
import android.Manifest; import android.app.*; import android.content.*; import android.content.pm.PackageManager; import android.os.*; import androidx.annotation.Nullable; import androidx.core.app.*; import com.google.android.gms.location.*;
public class TaximetLocationService extends Service{
 private static final String CH="taximet_gps"; private FusedLocationProviderClient fused; private LocationCallback cb;
 @Override public void onCreate(){super.onCreate();createChannel();startForeground(4402,notification());fused=LocationServices.getFusedLocationProviderClient(this);LocationRequest r=new LocationRequest.Builder(Priority.PRIORITY_HIGH_ACCURACY,1000L).setMinUpdateIntervalMillis(500L).setMaxUpdateDelayMillis(1500L).build();cb=new LocationCallback(){@Override public void onLocationResult(LocationResult x){if(x!=null)for(android.location.Location l:x.getLocations())publish(l);}};if(ActivityCompat.checkSelfPermission(this,Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED&&ActivityCompat.checkSelfPermission(this,Manifest.permission.ACCESS_COARSE_LOCATION)!=PackageManager.PERMISSION_GRANTED){error(1,"GPS chưa được cấp quyền");stopSelf();return;}fused.requestLocationUpdates(r,cb,Looper.getMainLooper());status();}
 private void publish(android.location.Location l){getSharedPreferences("taximet_gps",0).edit().putFloat("lat",(float)l.getLatitude()).putFloat("lon",(float)l.getLongitude()).putFloat("accuracy",Math.max(0,l.getAccuracy())).putFloat("speedMps",l.hasSpeed()?l.getSpeed():-1).putFloat("heading",l.hasBearing()?l.getBearing():-1).putLong("timestamp",l.getTime()).putBoolean("started",true).apply();Intent i=new Intent(TaximetLocationPlugin.ACTION_LOCATION).setPackage(getPackageName()).putExtra("latitude",l.getLatitude()).putExtra("longitude",l.getLongitude()).putExtra("accuracy",(double)Math.max(0,l.getAccuracy())).putExtra("speedMps",l.hasSpeed()?(double)l.getSpeed():-1d).putExtra("heading",l.hasBearing()?(double)l.getBearing():-1d).putExtra("timestamp",l.getTime());sendBroadcast(i);}
 private void error(int c,String m){sendBroadcast(new Intent(TaximetLocationPlugin.ACTION_ERROR).setPackage(getPackageName()).putExtra("code",c).putExtra("message",m));}
 private void status(){sendBroadcast(new Intent(TaximetLocationPlugin.ACTION_STATUS).setPackage(getPackageName()).putExtra("authorization","AUTHORIZED").putExtra("servicesEnabled",true).putExtra("started",true));}
 private void createChannel(){if(Build.VERSION.SDK_INT>=26)((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).createNotificationChannel(new NotificationChannel(CH,"TAXIMET PRO GPS",NotificationManager.IMPORTANCE_LOW));}
 private Notification notification(){Intent x=getPackageManager().getLaunchIntentForPackage(getPackageName());PendingIntent pi=x==null?null:PendingIntent.getActivity(this,0,x,PendingIntent.FLAG_IMMUTABLE|PendingIntent.FLAG_UPDATE_CURRENT);return new NotificationCompat.Builder(this,CH).setSmallIcon(android.R.drawable.ic_menu_mylocation).setContentTitle("TAXIMET PRO").setContentText("GPS đang hoạt động").setOngoing(true).setContentIntent(pi).setPriority(NotificationCompat.PRIORITY_LOW).build();}
 @Override public void onDestroy(){if(fused!=null&&cb!=null)fused.removeLocationUpdates(cb);getSharedPreferences("taximet_gps",0).edit().putBoolean("started",false).apply();super.onDestroy();}
 @Override public int onStartCommand(Intent i,int flags,int id){return START_STICKY;} @Nullable @Override public IBinder onBind(Intent i){return null;}
}
